/* Generates the UIx icon set (HAR-996) from Lucide's icon nodes.
 *
 *   node scripts/generate-icons.mjs <path to an installed lucide-react package>
 *
 * Reads scripts/icon-names.txt (Lucide React export names, legacy aliases allowed), resolves
 * each to its canonical Lucide glyph, and writes:
 *   src/icons/glyphs.ts      one `IconNode` const per glyph + ICON_GLYPHS (name → node)
 *   src/icons/components.ts  one component per glyph (`<Name>Icon`) + the alias names
 *   etc/icon-names.json      Lucide export name → UIx component + glyph name (for codemods)
 * Lucide is ISC; its licence travels with the package in THIRD_PARTY_NOTICES.md. Run it
 * again with a newer lucide-react to refresh paths or add names; the output is committed,
 * so the build has no Lucide dependency.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const lucide = process.argv[2];
if (!lucide) throw new Error('usage: node scripts/generate-icons.mjs <lucide-react package dir>');

const version = JSON.parse(readFileSync(join(lucide, 'package.json'), 'utf8')).version;
const index = readFileSync(join(lucide, 'dist/esm/lucide-react.mjs'), 'utf8');
const exportToGlyph = new Map();
for (const m of index.matchAll(/export \{([^}]+)\} from '\.\/icons\/([a-z0-9-]+)\.mjs';/g)) {
  for (const part of m[1].split(',')) exportToGlyph.set(part.trim().replace(/^default as /, ''), m[2]);
}

const pascal = (kebab) => kebab.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
// Glyph consts carry a prefix: some Lucide names (package, …) are reserved words in strict mode.
const camel = (kebab) => `glyph${pascal(kebab)}`;

const wanted = readFileSync(join(here, 'icon-names.txt'), 'utf8').split(/\s+/).filter(Boolean);
const glyphs = new Map(); // glyph → node
const names = new Map(); // requested export name → glyph
for (const name of wanted) {
  const glyph = exportToGlyph.get(name);
  if (!glyph) throw new Error(`lucide-react ${version} has no export ${name}`);
  names.set(name, glyph);
  if (glyphs.has(glyph)) continue;
  const src = readFileSync(join(lucide, 'dist/esm/icons', `${glyph}.mjs`), 'utf8');
  const start = src.indexOf('const __iconNode = ') + 'const __iconNode = '.length;
  const node = Function(`return (${src.slice(start, src.indexOf(';\nconst ', start))})`)();
  glyphs.set(glyph, node.map(([tag, { key, ...attrs }]) => [tag, attrs]));
}
const sortedGlyphs = [...glyphs.keys()].sort();

const header = `/* GENERATED by scripts/generate-icons.mjs from lucide-react ${version} (ISC, see THIRD_PARTY_NOTICES.md).
 * Do not edit by hand: add a name to scripts/icon-names.txt and regenerate. */\n`;

let glyphTs = `${header}import type { IconNode } from './types.js';\n\n`;
for (const g of sortedGlyphs) glyphTs += `export const ${camel(g)}: IconNode = ${JSON.stringify(glyphs.get(g))};\n`;
glyphTs += `\n/** Every glyph by its UIx name (the Lucide kebab-case name). Importing this pulls in the whole set. */\nexport const ICON_GLYPHS = {\n${sortedGlyphs.map((g) => `  '${g}': ${camel(g)},`).join('\n')}\n} as const;\n\n/** A glyph name for \`<Icon name>\`. */\nexport type IconName = keyof typeof ICON_GLYPHS;\n`;
writeFileSync(join(pkgRoot, 'src/icons/glyphs.ts'), glyphTs);

// Component per glyph, named after the canonical Lucide export; product aliases point at it.
const componentOf = (g) => `${pascal(g)}Icon`;
let compTs = `${header}import { createIcon } from './Icon.js';\nimport * as g from './glyphs.js';\n\n`;
for (const glyph of sortedGlyphs) compTs += `export const ${componentOf(glyph)} = /* @__PURE__ */ createIcon('${componentOf(glyph)}', g.${camel(glyph)});\n`;
const aliasLines = [];
for (const [name, glyph] of [...names].sort()) {
  const alias = `${name.replace(/Icon$/, '')}Icon`;
  if (alias !== componentOf(glyph) && !aliasLines.some((l) => l.startsWith(`export const ${alias} `))) aliasLines.push(`export const ${alias} = ${componentOf(glyph)};`);
}
if (aliasLines.length) compTs += `\n/* Older Lucide names the products import, kept so migration is a rename to <Name>Icon. */\n${aliasLines.join('\n')}\n`;
writeFileSync(join(pkgRoot, 'src/icons/components.ts'), compTs);

const map = Object.fromEntries([...names].sort().map(([name, glyph]) => [name, { component: `${name.replace(/Icon$/, '')}Icon`, glyph }]));
writeFileSync(join(pkgRoot, 'etc/icon-names.json'), `${JSON.stringify({ lucideReact: version, names: map }, null, 2)}\n`);
console.log(`lucide-react ${version}: ${sortedGlyphs.length} glyphs, ${names.size} names, ${aliasLines.length} aliases`);
